# Generated by Django 5.0.1 on 2025-07-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
