# Generated by Django 5.0.1 on 2025-07-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Project Image')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Project Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
