# Generated by Django 5.0.1 on 2025-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_portfolioproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Project Title'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='title_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='Project Title'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='category_fa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Project Title'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Project Title'),
        ),
        migrations.AddField(
            model_name='profile',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='profile',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_fa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title_fa',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
    ]
